micronaut:
    application:
        name: omar-ui-proto
---
micronaut:
    server:
        cors:
            enabled: true
---
micronaut:
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:public"