micronaut:
    application:
        name: server
---
micronaut:
    server:
        cors:
            enabled: true
---
micronaut:
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/omar-ui-proto/**"
                paths: "classpath:public"